apiVersion: v1
kind: Service
metadata:
  name: kubernetes-agent
  labels:
    app: kubernetes-agent
spec:
  # type: ClusterIP
  selector:
    app: kubernetes-agent
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http


